### ISSUE TITLE
data-value not working

### ISSUE THREAD

**Issue by AlexanderPease** [authy/authy-form-helpers#15]
Setting data-value does not work. The generated input remains blank. Tried for multiple values. Manually selecting an option does set correct value. 

Code: \<select id="authy-countries" data-value="57"></select>

Does not show a selection upon page loading.

**Comment by senekis** [comment]
The issue is with the CloudFlare CDN links because the library is outdated.

I updated the library in the CloudFlare CDN to version 2.3.

The new links are:
```
//cdnjs.cloudflare.com/ajax/libs/authy-form-helpers/2.3/form.authy.min.js
//cdnjs.cloudflare.com/ajax/libs/authy-form-helpers/2.3/form.authy.min.css
```

Thanks for report the issue :smiley:
