### ISSUE TITLE
placeholder attr not working for country code input

### ISSUE THREAD

**Issue by deegill** [authy/authy-form-helpers#18]
In version 2.3, even though I've included `placeholder=Country` in my `select` element, the placeholder text is not showing up in the browser.

Here's my html:
```<select id='authy-countries' name='user[country_code]' placeholder='Country'></select>```

Here is the DOM:
![image](https://cloud.githubusercontent.com/assets/2354251/9413947/149bd502-4803-11e5-8ad5-bb82c8b2a537.png)

Here it is rendered in the browser:
![image](https://cloud.githubusercontent.com/assets/2354251/9413984/3f07ee84-4803-11e5-8389-c8983a67e49b.png)

**Comment by chaadow** [comment]
Hi @deegill, it's just that by default it displays USA, but if you remove it manually, you will see that your placeholder is taken into account. 
In the readme, there is a section where you can set the default value. So I think if you set it to an empty string "", your placeholder will be displayed

**Comment by moisesweb** [comment]
@deegill #20 the placeholder behavior will be as you mentioned
