### ISSUE TITLE
Flag CSS selectors are too broad

### ISSUE THREAD

**Issue by Schweigi** [authy/authy-form-helpers#19]
The flag selectors `[class^="flag-"],[class*="flag-"]` (https://github.com/authy/authy-form-helpers/blob/master/src/flags.authy.css) apply to every CSS class containing the word `flag-`. Thus we have now images of all the flags on random places because some of our own CSS selectors contain the word `...flag-...` too.

A suggestion would be to use the prefix `authy` and change them to `[class^="authy-flag-"],[class*="authy-flag-"]` or to remove the `contains` selector `[class*="flag-"]`.

**Comment by danpal** [comment]
Will begin working on this. Thanks for reporting.

**Comment by moisesweb** [comment]
@Schweigi I'll fix that in #20
